import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import {
  memberRegistrationSchema,
  safeValidateMemberRegistration,
} from '@/lib/validations/member';

/**
 * POST /api/members/register
 * 
 * Register a new member after user authentication.
 * 
 * Requirements:
 * - User must be authenticated (session required)
 * - user_id will be set to auth.uid() (enforced by RLS policy)
 * - koperasi_id must be configured in environment
 * - nomor_anggota is auto-generated by database trigger
 * 
 * Security:
 * - RLS policy enforces user_id = auth.uid()
 * - Input validation via Zod schema
 * - Server-side only (no client-side DB access)
 */
export async function POST(request: NextRequest) {
  try {
    // 1. Get authenticated user session
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized. Please login first.' },
        { status: 401 }
      );
    }

    // 2. Parse and validate request body
    const body = await request.json();
    const validation = safeValidateMemberRegistration(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.errors.map((err) => ({
            field: err.path.join('.'),
            message: err.message,
          })),
        },
        { status: 400 }
      );
    }

    const validatedData = validation.data;

    // 3. Get koperasi_id from environment or config
    let koperasiId = process.env.KOPERASI_ID;

    // If not in env, try to fetch the first one from DB
    if (!koperasiId) {
        const { data: koperasiData } = await supabase
            .from('koperasi')
            .select('id')
            .limit(1)
            .single();
        
        if (koperasiData) {
            koperasiId = koperasiData.id;
        }
    }

    // If still no ID (and table is empty), handle error or use fallback
    // In a real app, this should be a critical configuration error
    if (!koperasiId) {
      // Create a default Koperasi automatically if none exists (Auto-Seeding for MVP)
      const { data: newKoperasi, error: createError } = await supabase
        .from('koperasi')
        .insert({
           nama: 'Koperasi Merah Putih',
           nomor_badan_hukum: 'BH-001-' + Date.now(),
           tanggal_berdiri: new Date().toISOString(),
           alamat: 'Jl. Merah Putih No. 1',
           kelurahan: 'Duri Kosambi',
           kecamatan: 'Cengkareng',
           kota: 'Jakarta Barat',
           provinsi: 'DKI Jakarta',
           email: 'admin@koperasi.id',
           phone: '08123456789'
        })
        .select('id')
        .single();
      
      if (createError || !newKoperasi) {
          console.error("Failed to auto-seed koperasi:", createError);
          return NextResponse.json(
            { error: 'System configuration error: No Koperasi found and failed to create default.' },
            { status: 500 }
          );
      }
      koperasiId = newKoperasi.id;
    }

    // 4. Check if member already exists for this user
    const { data: existingMember } = await supabase
      .from('member')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (existingMember) {
      return NextResponse.json(
        { error: 'Member profile already exists for this user' },
        { status: 409 }
      );
    }

    // 5. Check if NIK already exists (unique constraint)
    const { data: existingNIK } = await supabase
      .from('member')
      .select('id')
      .eq('nik', validatedData.nik)
      .single();

    if (existingNIK) {
      return NextResponse.json(
        { error: 'NIK already registered' },
        { status: 409 }
      );
    }

    // 6. Insert member record
    // Note: nomor_anggota is auto-generated by database trigger
    // user_id is set to auth.uid() - RLS policy will enforce this
    const { data: member, error: insertError } = await supabase
      .from('member')
      .insert({
        koperasi_id: koperasiId,
        user_id: user.id, // Must match auth.uid() for RLS to pass
        nama_lengkap: validatedData.nama_lengkap,
        nik: validatedData.nik,
        phone: validatedData.phone,
        email: validatedData.email || null,
        alamat_lengkap: validatedData.alamat_lengkap,
        member_type: validatedData.member_type || 'regular',
        status: 'pending', // Default status
        created_by: user.id, // Audit trail
      })
      .select('id, nomor_anggota, nama_lengkap, nik, status, created_at')
      .single();

    if (insertError) {
      // Handle specific database errors
      if (insertError.code === '23505') {
        // Unique constraint violation
        if (insertError.message.includes('nik')) {
          return NextResponse.json(
            { error: 'NIK already registered' },
            { status: 409 }
          );
        }
        if (insertError.message.includes('user_id')) {
          return NextResponse.json(
            { error: 'Member profile already exists for this user' },
            { status: 409 }
          );
        }
      }

      // RLS policy violation (should not happen if user_id = auth.uid())
      if (insertError.code === '42501') {
        return NextResponse.json(
          {
            error: 'Permission denied. RLS policy violation.',
            details: 'User ID mismatch detected.',
          },
          { status: 403 }
        );
      }

      console.error('Database error:', insertError);
      return NextResponse.json(
        { error: 'Failed to create member record', details: insertError.message },
        { status: 500 }
      );
    }

    // 7. Auto-Assign Admin Role for First User (MVP Helper)
    // Check if this is the only member/user, if so, make them admin
    const { count: memberCount } = await supabase.from('member').select('*', { count: 'exact', head: true });
    
    if (memberCount === 1) { // This is the first member
        await supabase.from('user_role').insert({
            koperasi_id: koperasiId,
            user_id: user.id,
            member_id: member.id,
            role: 'admin'
        });
    } else {
         // Default role for others: Anggota
         await supabase.from('user_role').insert({
            koperasi_id: koperasiId,
            user_id: user.id,
            member_id: member.id,
            role: 'anggota'
        });
    }

    // 8. Return success response
    return NextResponse.json(
      {
        success: true,
        data: {
          id: member.id,
          nomor_anggota: member.nomor_anggota,
          nama_lengkap: member.nama_lengkap,
          nik: member.nik,
          status: member.status,
          created_at: member.created_at,
        },
        message: 'Member registration successful. Your profile is pending approval.',
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Unexpected error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// Only allow POST method
export async function GET() {
  return NextResponse.json(
    { error: 'Method not allowed. Use POST to register.' },
    { status: 405 }
  );
}



