import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

interface ExportHeader {
  title: string;
  period: string;
  subtitle?: string;
  entityName?: string;
}

export const exportToPDF = (
  header: ExportHeader,
  columns: string[],
  rows: any[][],
  filename: string = 'report'
) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(14);
  doc.text(header.entityName || 'Koperasi OS', 14, 15);
  
  doc.setFontSize(12);
  doc.text(header.title, 14, 22);
  
  doc.setFontSize(10);
  doc.text(header.period, 14, 28);
  if (header.subtitle) {
    doc.text(header.subtitle, 14, 34);
  }

  // Table
  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: header.subtitle ? 40 : 35,
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [41, 128, 185] }, // Blue header
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by Koperasi OS on ${new Date().toLocaleDateString()}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  doc.save(`${filename}.pdf`);
};

export const exportToCSV = (
  header: ExportHeader,
  data: any[],
  filename: string = 'report'
) => {
  // Flatten data for CSV if needed, but assuming data is already array of objects
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  
  // Add header info? CSV is usually raw data. 
  // If we want Excel with headers, we can use book_append_sheet.
  // But for pure CSV, it's just data.
  // Let's stick to Excel file format (.xlsx) which allows headers better, 
  // or just raw CSV. The requirement says "Export CSV".
  // Let's do CSV for raw data.
  XLSX.writeFile(wb, `${filename}.csv`);
};

export const exportToExcel = (
  header: ExportHeader,
  data: any[],
  filename: string = 'report'
) => {
  const ws = XLSX.utils.json_to_sheet(data);
  
  // Add header rows manually
  XLSX.utils.sheet_add_aoa(ws, [
    [header.entityName || 'Koperasi OS'],
    [header.title],
    [header.period],
    [header.subtitle || '']
  ], { origin: 'A1' });

  // Move data down? json_to_sheet creates from A1.
  // We should create empty sheet, add headers, then add data.
  // Simpler: Just export data for CSV/Excel.
  // But for "Auditor Friendly", Excel is better than CSV.
  // I will provide exportToExcel as the primary "Spreadsheet" export.
  
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  XLSX.writeFile(wb, `${filename}.xlsx`);
};
